### ISSUE TITLE
Push Customer from OMS to NetSuite

### ISSUE THREAD

**Issue by rehan3586** [hotwax/netsuite-integration#12]
We need to prepare a Customer CSV file with the following information.

1. External Id -> Shopify customer Id -> You can get this value from PartyIdentification
2. Individual -> T
3. First Name -> PartyDetail.FirstName
4. Last Name -> PartyDetail.LastName
5. status -> CUSTOMER-Closed Won
6. Phone -> TelecomNumber.countryCode + TelecomNumber.areaCode + TelecomNumber.contactNumber
7. Address -> PostalAddress.address1
8. City -> PostalAddress.city
9. State -> PostalAddress.stateProvinceGeoId
10. Zip -> PostalAddress.postalCode
11. Country -> PostalAddress.countryGeoId (We will have to transform country value from USA to US)
12. Addressee -> PostalAddress.toName
13. Default Shipping -> Yes
14. Default Billing -> Yes
15. Subsidiary -> 1

Note: We will get the Subsidiary value from the SystemProperty entity as this can be different on the NetSuite account.

When we prepare the feed for the customer, we will make a PartyIdentification entity record to filter out the customer which is already sent to NetSuite

**Comment by rehan3586** [comment]
[Customer_Test.csv](https://github.com/hotwax/netsuite-integration/files/11544399/Customer_Test.csv)

**Comment by rehan3586** [comment]
As per discussion with Deepak sir, we will not send customer address information while making customer records on NetSuite as we don't store customer addresses on OMS. 

Here is the final CSV information:

1. External Id -> Shopify customer Id -> You can get this value from PartyIdentification
2. Individual -> T
3. First Name -> PartyDetail.FirstName
4. Last Name -> PartyDetail.LastName
5. status -> CUSTOMER-Closed Won
6. Subsidiary -> 1

**Comment by rehan3586** [comment]
[Customer_Test.csv](https://github.com/hotwax/netsuite-integration/files/11571921/Customer_Test.csv)

**Comment by gurveenbagga** [comment]
As per discussion with @dixitdeepak,  
1. We will not send address details for the customer as OMS currently does not manage addresses for customers. - This looks good as it is added in the earlier comment as well.  
2. For the External Id, I think it was discussed to use HC Party ID instead of Shopify customer Id.
3. In the scenario if some failure occurs to create PartyIdentification record in HC for the customer detail being sent to NetSuite, and the same External ID is sent again in the next feed, what is the expected behavior?

@rehan3586 
Can you please check and confirm on points 2 & 3.

**Comment by rehan3586** [comment]
Hello @gurveenbagga,

#2. As per my last discussion with Aditya Patel, we decided to store shopifyCustomerId in PartyIdentfication instead of HC partyId because Celigo also uses shopifyCustomerId in the externalId of the customer. But we will discuss this once again with the team and finalize which id will be used.

#3. In that case, NetSuite will not create the record and return error 'Duplicate record exists' for the customer. This is expected behavior but we need to create a PartyIdentification record for the customer on the OMS side.

**Comment by rehan3586** [comment]
Here is the sample customer CSV file.

[Customer_Test.csv](https://github.com/hotwax/netsuite-integration/files/11632588/Customer_Test.csv)

**Comment by rehan3586** [comment]
Hello @gurveenbagga,

Here is the SFTP location for the customer feed.

/home/{SFTP_USER}/netsuite/customer/export

**Comment by rehan3586** [comment]
This task has been completed and working as expected. So I am closing it.
