### ISSUE TITLE
Push Purchase Order Receipt from OMS to NetSuite

### ISSUE THREAD

**Issue by rehan3586** [hotwax/netsuite-integration#9]
We need to prepare a JSON file that will contain the following information for received purchase orders.
1) ORDER_ID
2) LINE_ID
3) QUANTITY

Data model entities:
a) OrderHeader
b) Shipment
c) ShipmentReceipt

EntityCondition: 
a) orderTypeId = PURCHASE_ORDER
b) shipmentTypeId = PURCHASE_SHIPMENT
c) shipment statusId = PURCH_SHIP_RECEIVED

If any order doesn't receive at OMS, please add zero(0) in the quantity column with order_id and line_id. 

**Note:** We need to make sure that PurchaseOrderReceipt CSV file should not contain any record which has been already pushed to NetSuite. It will be similar to the implementation, we did for sales order fulfillment for Shopify.

**Comment by rehan3586** [comment]
[Purchase_Order_Receipt.csv](https://github.com/hotwax/netsuite-integration/files/11420447/Purchase_Order_Receipt.csv)

**Comment by gurveenbagga** [comment]
@rehan3586 

Some comments and questions from my end, can you let me know your inputs on these.

1. The **field mapping** for the CSV format with HC data will be as follows, please confirm.

    1. ORDER_ID - OrderHeader.externalId
    2. LINE_ID - OrderItem.externalId
    3. QUANTITY - sum(ShipmentReceipt.quantityAccepted)

2. For the quantity field in the CSV, if for a PO item with 10 quantity, 8 qty is accepted and 2 rejected, do we send 8 as the quantity in the CSV, or we still send 10?

3. For the below statement, do we always send all PO order items irrespective of whether it is received or not?
    > If any order doesn't receive at OMS, please add zero(0) in the quantity column with order_id and line_id.

4. How will below scenarios work if above is true?
    1. A PO with 3 Order Items, 2 items received today, do we send all 3 items in the CSV with third item quantity as 0?
    2. If the third item is received the next day, do we need to send all 3 items again in the CSV, wouldn't this create incorrect data at NetSuite end?
    
5. For below, discussed with @dixitdeepak , we will not maintain the history records, instead use the saved last run time concept and prepare CSV for the update in POs after it was last sent to NetSuite. 
    We will check the use of ShipmentReceipt.datetimeReceived field for this.
   > Note: We need to make sure that PurchaseOrderReceipt CSV file should not contain any record which has been already pushed to NetSuite. It will be similar to the implementation, we did for sales order fulfillment for Shopify.

**Comment by rehan3586** [comment]
Hello @gurveenbagga,

Here are the details:

1.  Field Mapping for the CSV file will be

- ORDER_ID -> OrderHeader.externalId
- PRODUCT_ID -> Product.internalName
- QUANTITY -> sum(ShipmentReceipt.quantityAccepted)

Now we don't need to send LINE_ID, we will identify the line_id in NS suitescript on the basis of product_id.

2. We have to send only accepted qty i.e. 8.

3. Please refer to the below example for the 3rd and 4th points.
i. If HC creates a PO with 4 items, we receive 2 items today then we will send all 4 items with the first 2 received items and the last two items with zero qty as these are not received or not available in the ShipmentReceipt entity.
ii. Now, we receive only the 3rd item by the next day, we will send the 3rd item with the received qty and the 4th item with zero qty. Here we will not send the first two items as we have already sent them to NS.
iii. If we receive the 4th Item, will send only 4th item with the received qty.

5. Looks good to me and will confirm with Aditya Patel. If there are any changes in the solution, will get back to you. For now, we can start the implementation with this solution.

**Comment by gurveenbagga** [comment]
> @rehan3586
> 
> Some comments and questions from my end, can you let me know your inputs on these.
> 
> 1. The **field mapping** for the CSV format with HC data will be as follows, please confirm.
>    
>    1. ORDER_ID - OrderHeader.externalId
>    2. LINE_ID - OrderItem.externalId
>    3. QUANTITY - sum(ShipmentReceipt.quantityAccepted)
> 2. For the quantity field in the CSV, if for a PO item with 10 quantity, 8 qty is accepted and 2 rejected, do we send 8 as the quantity in the CSV, or we still send 10?
> 3. For the below statement, do we always send all PO order items irrespective of whether it is received or not?
>    > If any order doesn't receive at OMS, please add zero(0) in the quantity column with order_id and line_id.
> 4. How will below scenarios work if above is true?
>    
>    1. A PO with 3 Order Items, 2 items received today, do we send all 3 items in the CSV with third item quantity as 0?
>    2. If the third item is received the next day, do we need to send all 3 items again in the CSV, wouldn't this create incorrect data at NetSuite end?
> 5. For below, discussed with @dixitdeepak , we will not maintain the history records, instead use the saved last run time concept and prepare CSV for the update in POs after it was last sent to NetSuite.
>    We will check the use of ShipmentReceipt.datetimeReceived field for this.
>    > Note: We need to make sure that PurchaseOrderReceipt CSV file should not contain any record which has been already pushed to NetSuite. It will be similar to the implementation, we did for sales order fulfillment for Shopify.

Just an update here, for point 5 , we will go by history creation records as we already have an entity "ShipmentItemHistory" whjch includes receiptId and can be used here to not send the same records again in multiple feeds.

**Comment by gurveenbagga** [comment]
Adding the required JSON format for NetSuite

```
[
  {
    "order_id": "36352",
    "items": [
      {
        "line_id": "1",
        "quantity": "2"
      },
      {
        "line_id": "2",
        "quantity": "3"
      },
      {
        "line_id": "3",
        "quantity": "5"
      }
    ]
  },
  {
    "order_id": "36353",
    "items": [
      {
        "line_id": "1",
        "quantity": "5"
      },
      {
        "line_id": "2",
        "quantity": "20"
      }
    ]
  }
]
```

**Comment by rehan3586** [comment]
We have verified the purchase order receipt feed and it is working fine. So we are closing the ticket
